version: '3.1'

services:

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: coffeeshop
      POSTGRES_DB: coffeeshop
    volumes:
      - ./initdb.d/coffeeshop.sql:/docker-entrypoint-initdb.d/coffeeshop.sql
    ports:
      - "5432:5432"

