// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)
// swagger:model
type Customer struct {
	// the id for this user
	//
	// required: true
	// min: 1
	CustomerID int64            `json:"customerID"`
	FullName   string           `json:"fullName"`
	// returns the wrong data type (string) in the OpenAPI definitions.
	// swagger:strfmt date-time
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

type Order struct {
	OrderID    int64            `json:"orderID"`
	CustomerID int64            `json:"customerID"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

type OrdersDetail struct {
	OrderID   int64            `json:"orderID"`
	ProductID int64            `json:"productID"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Product struct {
	ProductID   int64   `json:"productID"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float32 `json:"price"`
}
